source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'
use_frameworks!

target 'testing-demo' do
  
  target 'testing-demo-unit-tests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
  end
  
end
